### ISSUE TITLE
Error returning file nodeRef in multi-tenant environment

### ISSUE THREAD

**Issue by t-dias** [ArawaFr/libreoffice-online-repo#5]
Hello,
I'm trying to use the module in an alfresco multi tenant environment, but I'm getting some troubles.

The first problem was an "Authorization 'Bearer' not supported"  exception. For that I found a workaround adding a filter in alfresco that skip the bearer token for the lool url patterns.
`public class AuthenticationFilter implements Filter { (...) }`

Second and what I'm not getting any solution or workaround is about noderef not found exception, maybe because the tenant domain is not the right one in the request. 

> 2019-02-18 17:04:48,048  ERROR [extensions.webscripts.AbstractRuntime] [http-apr-8080-exec-7] Exception from executeScript: 01180000 error returning file nodeRef
alfresco_1_aa378c3b5b4b |  org.springframework.extensions.webscripts.WebScriptException: 01180000 error returning file nodeRef
alfresco_1_aa378c3b5b4b | 	at dk.magenta.libreoffice.online.LOOLCheckFileInfoWebScript.executeImpl(LOOLCheckFileInfoWebScript.java:108)
alfresco_1_aa378c3b5b4b | 	at org.springframework.extensions.webscripts.DeclarativeWebScript.execute(DeclarativeWebScript.java:64)
alfresco_1_aa378c3b5b4b | 	at org.alfresco.repo.web.scripts.RepositoryContainer$3.execute(RepositoryContainer.java:519)
alfresco_1_aa378c3b5b4b | 	at org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:464)
alfresco_1_aa378c3b5b4b | 	at org.alfresco.repo.web.scripts.RepositoryContainer.transactionedExecute(RepositoryContainer.java:587)
alfresco_1_aa378c3b5b4b | 	at org.alfresco.repo.web.scripts.RepositoryContainer.transactionedExecuteAs(RepositoryContainer.java:656)
alfresco_1_aa378c3b5b4b | 	at org.alfresco.repo.web.scripts.RepositoryContainer.executeScriptInternal(RepositoryContainer.java:355)
alfresco_1_aa378c3b5b4b | 	at org.alfresco.repo.web.scripts.RepositoryContainer.executeScript(RepositoryContainer.java:308)
(...)

I already tried using `AuthenticationUtil.setFullyAuthenticatedUser(...)` in some places but continues failing when I try to get two files with two tenants.
 
I don't know if you already tried with multi-tenant environment.
Any help will be very appreciated.
Thanks.

**Comment by jeci-sarl** [comment]
Hi,
Could you provide full stacktrace exception, I don't see the "cause by", the source error.

regards
